log_level: debug 
log_dir: ./log
log_prefix: match
log_stderr: true 

rpc_addr: 127.0.0.1
rpc_port: 37001
health_port: 37002
rpc_server_name: match
#health_port: 17001


redis_addr: 127.0.0.1:6379
redis_passwd: 

consul_addr: 127.0.0.1:8500

nsqd_addr: 127.0.0.1:4150
nsqlookupd_addrs: 
  - 127.0.0.1:4161

node: 1


# http 监听地址
http_addr: 0.0.0.0:37002