// Code generated by protoc-gen-go. DO NOT EDIT.
// source: match.proto

/*
Package match is a generated protocol buffer package.

It is generated from these files:
	match.proto

It has these top-level messages:
	MatchReq
	MatchRsp
	MatchDeskContinueReq
	MatchDeskContinueRsp
	MatchContinueDeskDimissNtf
*/
package match

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "steve/client_pb/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MatchReq 匹配请求
type MatchReq struct {
	Reserve          *uint32                        `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	GameId           *common.GameId                 `protobuf:"varint,2,opt,name=game_id,json=gameId,enum=common.GameId" json:"game_id,omitempty"`
	Location         []*common.GeographicalLocation `protobuf:"bytes,3,rep,name=location" json:"location,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *MatchReq) Reset()                    { *m = MatchReq{} }
func (m *MatchReq) String() string            { return proto.CompactTextString(m) }
func (*MatchReq) ProtoMessage()               {}
func (*MatchReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MatchReq) GetReserve() uint32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

func (m *MatchReq) GetGameId() common.GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return common.GameId_GAMEID_XUELIU
}

func (m *MatchReq) GetLocation() []*common.GeographicalLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

// MatchRsp 匹配应答
type MatchRsp struct {
	ErrCode          *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc          *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MatchRsp) Reset()                    { *m = MatchRsp{} }
func (m *MatchRsp) String() string            { return proto.CompactTextString(m) }
func (*MatchRsp) ProtoMessage()               {}
func (*MatchRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MatchRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MatchRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

// MatchDeskContinueReq 续局请求
type MatchDeskContinueReq struct {
	GameId           *common.GameId                 `protobuf:"varint,1,opt,name=game_id,json=gameId,enum=common.GameId" json:"game_id,omitempty"`
	Location         []*common.GeographicalLocation `protobuf:"bytes,2,rep,name=location" json:"location,omitempty"`
	Cancel           *bool                          `protobuf:"varint,3,opt,name=cancel" json:"cancel,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *MatchDeskContinueReq) Reset()                    { *m = MatchDeskContinueReq{} }
func (m *MatchDeskContinueReq) String() string            { return proto.CompactTextString(m) }
func (*MatchDeskContinueReq) ProtoMessage()               {}
func (*MatchDeskContinueReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MatchDeskContinueReq) GetGameId() common.GameId {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return common.GameId_GAMEID_XUELIU
}

func (m *MatchDeskContinueReq) GetLocation() []*common.GeographicalLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *MatchDeskContinueReq) GetCancel() bool {
	if m != nil && m.Cancel != nil {
		return *m.Cancel
	}
	return false
}

// MatchDeskContinueRsp 续局应答
type MatchDeskContinueRsp struct {
	ErrCode          *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc          *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MatchDeskContinueRsp) Reset()                    { *m = MatchDeskContinueRsp{} }
func (m *MatchDeskContinueRsp) String() string            { return proto.CompactTextString(m) }
func (*MatchDeskContinueRsp) ProtoMessage()               {}
func (*MatchDeskContinueRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MatchDeskContinueRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MatchDeskContinueRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

// MatchContinueDeskDimissNtf 续局牌桌解散通知
type MatchContinueDeskDimissNtf struct {
	Reserve          *int32 `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MatchContinueDeskDimissNtf) Reset()                    { *m = MatchContinueDeskDimissNtf{} }
func (m *MatchContinueDeskDimissNtf) String() string            { return proto.CompactTextString(m) }
func (*MatchContinueDeskDimissNtf) ProtoMessage()               {}
func (*MatchContinueDeskDimissNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MatchContinueDeskDimissNtf) GetReserve() int32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

func init() {
	proto.RegisterType((*MatchReq)(nil), "match.MatchReq")
	proto.RegisterType((*MatchRsp)(nil), "match.MatchRsp")
	proto.RegisterType((*MatchDeskContinueReq)(nil), "match.MatchDeskContinueReq")
	proto.RegisterType((*MatchDeskContinueRsp)(nil), "match.MatchDeskContinueRsp")
	proto.RegisterType((*MatchContinueDeskDimissNtf)(nil), "match.MatchContinueDeskDimissNtf")
}

func init() { proto.RegisterFile("match.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0x87, 0xe5, 0x56, 0x69, 0xf2, 0xba, 0x2f, 0x1d, 0x2c, 0xfe, 0x84, 0x8a, 0x21, 0xca, 0x42,
	0xa6, 0x56, 0xea, 0x80, 0x18, 0x11, 0x8d, 0x84, 0x90, 0x0a, 0x83, 0x47, 0x96, 0xc8, 0x38, 0x47,
	0x6a, 0x11, 0xdb, 0xc1, 0x36, 0xfd, 0x0a, 0xcc, 0x7c, 0x63, 0x14, 0x37, 0x89, 0x10, 0x62, 0x00,
	0x26, 0xeb, 0xee, 0x7e, 0x7a, 0xf4, 0x9c, 0xce, 0x78, 0x2a, 0x99, 0xe3, 0xdb, 0x45, 0x63, 0xb4,
	0xd3, 0x24, 0xf0, 0xc5, 0xfc, 0x3f, 0xd7, 0x52, 0x6a, 0xb5, 0x6f, 0xa6, 0x6f, 0x08, 0x47, 0x77,
	0x6d, 0x9f, 0xc2, 0x0b, 0x89, 0x71, 0x68, 0xc0, 0x82, 0xd9, 0x41, 0x8c, 0x12, 0x94, 0x1d, 0xd0,
	0xbe, 0x24, 0xe7, 0x38, 0xac, 0x98, 0x84, 0x42, 0x94, 0xf1, 0x28, 0x41, 0xd9, 0x6c, 0x35, 0x5b,
	0x74, 0x98, 0x1b, 0x26, 0xe1, 0xb6, 0xa4, 0x93, 0xca, 0xbf, 0xe4, 0x12, 0x47, 0xb5, 0xe6, 0xcc,
	0x09, 0xad, 0xe2, 0x71, 0x32, 0xce, 0xa6, 0xab, 0xb3, 0x21, 0x09, 0xba, 0x32, 0xac, 0xd9, 0x0a,
	0xce, 0xea, 0x4d, 0x97, 0xa1, 0x43, 0x3a, 0xbd, 0xea, 0x45, 0x6c, 0x43, 0x4e, 0x71, 0x04, 0xc6,
	0x14, 0x5c, 0x97, 0x7b, 0x93, 0x80, 0x86, 0x60, 0xcc, 0x5a, 0x97, 0xd0, 0x8f, 0x4a, 0xb0, 0xdc,
	0xab, 0xfc, 0xf3, 0xa3, 0x1c, 0x2c, 0x4f, 0xdf, 0x11, 0x3e, 0xf4, 0x88, 0x1c, 0xec, 0xf3, 0x5a,
	0x2b, 0x27, 0xd4, 0x2b, 0xb4, 0x7b, 0x7d, 0xb2, 0x47, 0x3f, 0xb6, 0x1f, 0xfd, 0xc6, 0x9e, 0x1c,
	0xe3, 0x09, 0x67, 0x8a, 0x43, 0x1d, 0x8f, 0x13, 0x94, 0x45, 0xb4, 0xab, 0xd2, 0xcd, 0x77, 0x4a,
	0x7f, 0xde, 0xf0, 0x02, 0xcf, 0x3d, 0xad, 0x27, 0xb5, 0xd4, 0x5c, 0x48, 0x61, 0xed, 0xbd, 0x7b,
	0xfa, 0x7a, 0xbe, 0x60, 0x38, 0xdf, 0xf5, 0xc9, 0xc3, 0x91, 0x75, 0xb0, 0x83, 0x25, 0xaf, 0x05,
	0x28, 0x57, 0x34, 0x8f, 0x4b, 0xff, 0x19, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x85, 0x86, 0xc0,
	0xbe, 0x21, 0x02, 0x00, 0x00,
}
