// Code generated by protoc-gen-go. DO NOT EDIT.
// source: match.proto

package match

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "steve/client_pb/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MatchReq 匹配请求
type MatchReq struct {
	Reserve          *uint32                        `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	GameId           *uint32                        `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId          *uint32                        `protobuf:"varint,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	Location         []*common.GeographicalLocation `protobuf:"bytes,4,rep,name=location" json:"location,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *MatchReq) Reset()                    { *m = MatchReq{} }
func (m *MatchReq) String() string            { return proto.CompactTextString(m) }
func (*MatchReq) ProtoMessage()               {}
func (*MatchReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MatchReq) GetReserve() uint32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

func (m *MatchReq) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *MatchReq) GetLevelId() uint32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

func (m *MatchReq) GetLocation() []*common.GeographicalLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

// MatchRsp 匹配应答
type MatchRsp struct {
	ErrCode          *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc          *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	GameId           *uint32 `protobuf:"varint,3,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId          *uint32 `protobuf:"varint,4,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MatchRsp) Reset()                    { *m = MatchRsp{} }
func (m *MatchRsp) String() string            { return proto.CompactTextString(m) }
func (*MatchRsp) ProtoMessage()               {}
func (*MatchRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *MatchRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MatchRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func (m *MatchRsp) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *MatchRsp) GetLevelId() uint32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

// DeskPlayerInfo 桌子玩家数据
type DeskPlayerInfo struct {
	PlayerId         *uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Coin             *int64  `protobuf:"varint,3,opt,name=coin" json:"coin,omitempty"`
	Seat             *int32  `protobuf:"varint,4,opt,name=seat" json:"seat,omitempty"`
	Gender           *uint32 `protobuf:"varint,5,opt,name=gender" json:"gender,omitempty"`
	Avatar           *string `protobuf:"bytes,6,opt,name=avatar" json:"avatar,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeskPlayerInfo) Reset()                    { *m = DeskPlayerInfo{} }
func (m *DeskPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*DeskPlayerInfo) ProtoMessage()               {}
func (*DeskPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *DeskPlayerInfo) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *DeskPlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *DeskPlayerInfo) GetCoin() int64 {
	if m != nil && m.Coin != nil {
		return *m.Coin
	}
	return 0
}

func (m *DeskPlayerInfo) GetSeat() int32 {
	if m != nil && m.Seat != nil {
		return *m.Seat
	}
	return 0
}

func (m *DeskPlayerInfo) GetGender() uint32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *DeskPlayerInfo) GetAvatar() string {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return ""
}

// 匹配成功时的创建桌子消息
type MatchSucCreateDeskNtf struct {
	Players          []*DeskPlayerInfo `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	GameId           *uint32           `protobuf:"varint,2,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	LevelId          *uint32           `protobuf:"varint,3,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MatchSucCreateDeskNtf) Reset()                    { *m = MatchSucCreateDeskNtf{} }
func (m *MatchSucCreateDeskNtf) String() string            { return proto.CompactTextString(m) }
func (*MatchSucCreateDeskNtf) ProtoMessage()               {}
func (*MatchSucCreateDeskNtf) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *MatchSucCreateDeskNtf) GetPlayers() []*DeskPlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *MatchSucCreateDeskNtf) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *MatchSucCreateDeskNtf) GetLevelId() uint32 {
	if m != nil && m.LevelId != nil {
		return *m.LevelId
	}
	return 0
}

// MatchDeskContinueReq 续局请求
type MatchDeskContinueReq struct {
	GameId           *uint32                        `protobuf:"varint,1,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	Location         []*common.GeographicalLocation `protobuf:"bytes,2,rep,name=location" json:"location,omitempty"`
	Cancel           *bool                          `protobuf:"varint,3,opt,name=cancel" json:"cancel,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *MatchDeskContinueReq) Reset()                    { *m = MatchDeskContinueReq{} }
func (m *MatchDeskContinueReq) String() string            { return proto.CompactTextString(m) }
func (*MatchDeskContinueReq) ProtoMessage()               {}
func (*MatchDeskContinueReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *MatchDeskContinueReq) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *MatchDeskContinueReq) GetLocation() []*common.GeographicalLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *MatchDeskContinueReq) GetCancel() bool {
	if m != nil && m.Cancel != nil {
		return *m.Cancel
	}
	return false
}

// MatchDeskContinueRsp 续局应答
type MatchDeskContinueRsp struct {
	ErrCode          *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc          *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MatchDeskContinueRsp) Reset()                    { *m = MatchDeskContinueRsp{} }
func (m *MatchDeskContinueRsp) String() string            { return proto.CompactTextString(m) }
func (*MatchDeskContinueRsp) ProtoMessage()               {}
func (*MatchDeskContinueRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *MatchDeskContinueRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *MatchDeskContinueRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

// MatchContinueDeskDimissNtf 续局牌桌解散通知
type MatchContinueDeskDimissNtf struct {
	Reserve          *int32 `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MatchContinueDeskDimissNtf) Reset()                    { *m = MatchContinueDeskDimissNtf{} }
func (m *MatchContinueDeskDimissNtf) String() string            { return proto.CompactTextString(m) }
func (*MatchContinueDeskDimissNtf) ProtoMessage()               {}
func (*MatchContinueDeskDimissNtf) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *MatchContinueDeskDimissNtf) GetReserve() int32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

// CancelMatchReq 取消匹配请求
type CancelMatchReq struct {
	Reserve          *uint32 `protobuf:"varint,1,opt,name=reserve" json:"reserve,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CancelMatchReq) Reset()                    { *m = CancelMatchReq{} }
func (m *CancelMatchReq) String() string            { return proto.CompactTextString(m) }
func (*CancelMatchReq) ProtoMessage()               {}
func (*CancelMatchReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *CancelMatchReq) GetReserve() uint32 {
	if m != nil && m.Reserve != nil {
		return *m.Reserve
	}
	return 0
}

// CancelMatchRsp 取消匹配应答
type CancelMatchRsp struct {
	ErrCode          *int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrDesc          *string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc" json:"err_desc,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CancelMatchRsp) Reset()                    { *m = CancelMatchRsp{} }
func (m *CancelMatchRsp) String() string            { return proto.CompactTextString(m) }
func (*CancelMatchRsp) ProtoMessage()               {}
func (*CancelMatchRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *CancelMatchRsp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *CancelMatchRsp) GetErrDesc() string {
	if m != nil && m.ErrDesc != nil {
		return *m.ErrDesc
	}
	return ""
}

func init() {
	proto.RegisterType((*MatchReq)(nil), "match.MatchReq")
	proto.RegisterType((*MatchRsp)(nil), "match.MatchRsp")
	proto.RegisterType((*DeskPlayerInfo)(nil), "match.DeskPlayerInfo")
	proto.RegisterType((*MatchSucCreateDeskNtf)(nil), "match.MatchSucCreateDeskNtf")
	proto.RegisterType((*MatchDeskContinueReq)(nil), "match.MatchDeskContinueReq")
	proto.RegisterType((*MatchDeskContinueRsp)(nil), "match.MatchDeskContinueRsp")
	proto.RegisterType((*MatchContinueDeskDimissNtf)(nil), "match.MatchContinueDeskDimissNtf")
	proto.RegisterType((*CancelMatchReq)(nil), "match.CancelMatchReq")
	proto.RegisterType((*CancelMatchRsp)(nil), "match.CancelMatchRsp")
}

func init() { proto.RegisterFile("match.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0x95, 0xee, 0x66, 0x93, 0xba, 0xd0, 0x83, 0xc5, 0xd2, 0x50, 0x38, 0x54, 0x3e, 0x55,
	0x1c, 0x76, 0x25, 0x0e, 0x88, 0x33, 0x59, 0x81, 0x22, 0x15, 0x84, 0xcc, 0x8d, 0xcb, 0xca, 0xd8,
	0xd3, 0xad, 0x45, 0x62, 0x07, 0xdb, 0x8d, 0x84, 0xc4, 0x85, 0x57, 0xe0, 0xc6, 0xdb, 0x22, 0x4f,
	0x92, 0x6a, 0x83, 0x40, 0xa8, 0x7b, 0xf3, 0x3f, 0x33, 0x99, 0xff, 0xcb, 0x8c, 0x4d, 0x4e, 0x1a,
	0x11, 0xe4, 0xcd, 0xaa, 0x75, 0x36, 0x58, 0x9a, 0xa2, 0x38, 0x7f, 0x20, 0x6d, 0xd3, 0x58, 0xd3,
	0x07, 0xd9, 0xcf, 0x84, 0xe4, 0xef, 0x62, 0x9c, 0xc3, 0x57, 0x5a, 0x90, 0xcc, 0x81, 0x07, 0xd7,
	0x41, 0x91, 0x5c, 0x24, 0x97, 0x0f, 0xf9, 0x28, 0xe9, 0x19, 0xc9, 0x76, 0xa2, 0x81, 0xad, 0x56,
	0xc5, 0x11, 0x66, 0x16, 0x51, 0x56, 0x8a, 0x3e, 0x21, 0x79, 0x0d, 0x1d, 0xd4, 0x31, 0x33, 0xeb,
	0xbf, 0x41, 0x5d, 0x29, 0xfa, 0x8a, 0xe4, 0xb5, 0x95, 0x22, 0x68, 0x6b, 0x8a, 0xf9, 0xc5, 0xec,
	0xf2, 0xe4, 0xc5, 0xb3, 0xd5, 0xe0, 0xfd, 0x16, 0xec, 0xce, 0x89, 0xf6, 0x46, 0x4b, 0x51, 0x5f,
	0x0d, 0x35, 0xfc, 0xae, 0x9a, 0x85, 0x91, 0xc9, 0xb7, 0xd1, 0x00, 0x9c, 0xdb, 0x4a, 0xab, 0x7a,
	0xa8, 0x94, 0x67, 0xe0, 0x5c, 0x69, 0x15, 0x8c, 0x29, 0x05, 0x5e, 0x22, 0xd5, 0x31, 0xa6, 0x36,
	0xe0, 0xe5, 0x3e, 0xef, 0xec, 0x9f, 0xbc, 0xf3, 0x09, 0x2f, 0xfb, 0x95, 0x90, 0xd3, 0x0d, 0xf8,
	0x2f, 0x1f, 0x6a, 0xf1, 0x0d, 0x5c, 0x65, 0xae, 0x2d, 0x7d, 0x4a, 0x8e, 0x5b, 0x54, 0xb1, 0x3c,
	0xba, 0xcf, 0x79, 0xde, 0x07, 0x2a, 0x45, 0x29, 0x99, 0x1b, 0xd1, 0xc0, 0x60, 0x8d, 0xe7, 0x18,
	0x93, 0x56, 0x1b, 0x34, 0x9d, 0x71, 0x3c, 0xc7, 0x98, 0x07, 0x11, 0xd0, 0x2e, 0xe5, 0x78, 0xa6,
	0x8f, 0xc9, 0x62, 0x07, 0x46, 0x81, 0x2b, 0xd2, 0x01, 0x0f, 0x55, 0x8c, 0x8b, 0x4e, 0x04, 0xe1,
	0x8a, 0x05, 0x76, 0x1d, 0x14, 0xfb, 0x4e, 0x96, 0x38, 0x91, 0x8f, 0xb7, 0xb2, 0x74, 0x20, 0x02,
	0x44, 0xd0, 0xf7, 0xe1, 0x9a, 0xae, 0x49, 0xd6, 0x03, 0xf9, 0x22, 0xc1, 0x19, 0x2f, 0x57, 0xfd,
	0xce, 0xa7, 0x7f, 0xc2, 0xc7, 0xaa, 0x43, 0x36, 0xc9, 0x7e, 0x24, 0xe4, 0x11, 0xda, 0xc7, 0xa6,
	0xa5, 0x35, 0x41, 0x9b, 0x5b, 0x88, 0x17, 0x66, 0xaf, 0x59, 0x32, 0x69, 0xb6, 0xbf, 0xfb, 0xa3,
	0xfb, 0xec, 0x3e, 0x4e, 0x40, 0x0a, 0x23, 0xa1, 0x46, 0x88, 0x9c, 0x0f, 0x8a, 0x5d, 0xfd, 0x0d,
	0xe1, 0xd0, 0xfb, 0xc1, 0x5e, 0x92, 0x73, 0xec, 0x36, 0x76, 0x8a, 0x5d, 0x37, 0xba, 0xd1, 0xde,
	0xc7, 0xa1, 0xfe, 0xf1, 0x0e, 0xd2, 0xbb, 0x77, 0xc0, 0x9e, 0x93, 0xd3, 0x12, 0x79, 0xfe, 0xff,
	0x66, 0xd8, 0x9b, 0x69, 0xed, 0xa1, 0xac, 0xaf, 0xcf, 0x3e, 0x2d, 0x7d, 0x80, 0x0e, 0xd6, 0xb2,
	0xd6, 0x60, 0xc2, 0xb6, 0xfd, 0xbc, 0xc6, 0x15, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x37, 0x38,
	0x9b, 0x97, 0xde, 0x03, 0x00, 0x00,
}
