// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package login is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	BindInfo
	LoginData
	AuthCodeReq
	AuthCodeRsp
	LoginAuthReq
	LoginAuthRsp
	AccountSysLoginRequestData
*/
package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_SUCCESS           ErrorCode = 0
	ErrorCode_ABNORMAL          ErrorCode = 1
	ErrorCode_ERR_EXPIRE_TOKEN  ErrorCode = 101
	ErrorCode_ERR_INVALID_TOKEN ErrorCode = 102
)

var ErrorCode_name = map[int32]string{
	0:   "SUCCESS",
	1:   "ABNORMAL",
	101: "ERR_EXPIRE_TOKEN",
	102: "ERR_INVALID_TOKEN",
}
var ErrorCode_value = map[string]int32{
	"SUCCESS":           0,
	"ABNORMAL":          1,
	"ERR_EXPIRE_TOKEN":  101,
	"ERR_INVALID_TOKEN": 102,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 登录方式
type LoginType int32

const (
	LoginType_PHONE_LOGIN   LoginType = 0
	LoginType_WECHAT_LOGIN  LoginType = 1
	LoginType_VISITOR_LOGIN LoginType = 2
)

var LoginType_name = map[int32]string{
	0: "PHONE_LOGIN",
	1: "WECHAT_LOGIN",
	2: "VISITOR_LOGIN",
}
var LoginType_value = map[string]int32{
	"PHONE_LOGIN":   0,
	"WECHAT_LOGIN":  1,
	"VISITOR_LOGIN": 2,
}

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}
func (x LoginType) String() string {
	return proto.EnumName(LoginType_name, int32(x))
}
func (x *LoginType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LoginType_value, data, "LoginType")
	if err != nil {
		return err
	}
	*x = LoginType(value)
	return nil
}
func (LoginType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 渠道
type ChannelType int32

const (
	ChannelType_PHONE   ChannelType = 0
	ChannelType_WECHAT  ChannelType = 1
	ChannelType_VISITOR ChannelType = 2
)

var ChannelType_name = map[int32]string{
	0: "PHONE",
	1: "WECHAT",
	2: "VISITOR",
}
var ChannelType_value = map[string]int32{
	"PHONE":   0,
	"WECHAT":  1,
	"VISITOR": 2,
}

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}
func (x ChannelType) String() string {
	return proto.EnumName(ChannelType_name, int32(x))
}
func (x *ChannelType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChannelType_value, data, "ChannelType")
	if err != nil {
		return err
	}
	*x = ChannelType(value)
	return nil
}
func (ChannelType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 验证码发送场景
type AuthCodeSendScene int32

const (
	AuthCodeSendScene_REGISTER        AuthCodeSendScene = 1
	AuthCodeSendScene_RESET_PASSWORD  AuthCodeSendScene = 2
	AuthCodeSendScene_RESET_CELLPHONE AuthCodeSendScene = 3
	AuthCodeSendScene_NEW_HALL_LOGIN  AuthCodeSendScene = 4
	AuthCodeSendScene_BIND_WECHAT     AuthCodeSendScene = 10
)

var AuthCodeSendScene_name = map[int32]string{
	1:  "REGISTER",
	2:  "RESET_PASSWORD",
	3:  "RESET_CELLPHONE",
	4:  "NEW_HALL_LOGIN",
	10: "BIND_WECHAT",
}
var AuthCodeSendScene_value = map[string]int32{
	"REGISTER":        1,
	"RESET_PASSWORD":  2,
	"RESET_CELLPHONE": 3,
	"NEW_HALL_LOGIN":  4,
	"BIND_WECHAT":     10,
}

func (x AuthCodeSendScene) Enum() *AuthCodeSendScene {
	p := new(AuthCodeSendScene)
	*p = x
	return p
}
func (x AuthCodeSendScene) String() string {
	return proto.EnumName(AuthCodeSendScene_name, int32(x))
}
func (x *AuthCodeSendScene) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AuthCodeSendScene_value, data, "AuthCodeSendScene")
	if err != nil {
		return err
	}
	*x = AuthCodeSendScene(value)
	return nil
}
func (AuthCodeSendScene) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 绑定信息根据绑定类型为不同数据结构，无绑定类型时为空数组
type BindInfo struct {
	WcAppid          *string `protobuf:"bytes,1,opt,name=wc_appid,json=wcAppid" json:"wc_appid,omitempty"`
	WcOpenid         *string `protobuf:"bytes,2,opt,name=wc_openid,json=wcOpenid" json:"wc_openid,omitempty"`
	WcUnionid        *string `protobuf:"bytes,3,opt,name=wc_unionid,json=wcUnionid" json:"wc_unionid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BindInfo) Reset()                    { *m = BindInfo{} }
func (m *BindInfo) String() string            { return proto.CompactTextString(m) }
func (*BindInfo) ProtoMessage()               {}
func (*BindInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BindInfo) GetWcAppid() string {
	if m != nil && m.WcAppid != nil {
		return *m.WcAppid
	}
	return ""
}

func (m *BindInfo) GetWcOpenid() string {
	if m != nil && m.WcOpenid != nil {
		return *m.WcOpenid
	}
	return ""
}

func (m *BindInfo) GetWcUnionid() string {
	if m != nil && m.WcUnionid != nil {
		return *m.WcUnionid
	}
	return ""
}

// 登录数据
type LoginData struct {
	Type             *LoginType   `protobuf:"varint,1,opt,name=type,enum=login.LoginType" json:"type,omitempty"`
	Channel          *ChannelType `protobuf:"varint,2,opt,name=channel,enum=login.ChannelType" json:"channel,omitempty"`
	Username         *string      `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	DymcCode         *string      `protobuf:"bytes,4,opt,name=dymc_code,json=dymcCode" json:"dymc_code,omitempty"`
	Password         *string      `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	ProId            *uint64      `protobuf:"varint,6,opt,name=pro_id,json=proId" json:"pro_id,omitempty"`
	CityId           *uint64      `protobuf:"varint,7,opt,name=city_id,json=cityId" json:"city_id,omitempty"`
	BindInfo         *BindInfo    `protobuf:"bytes,8,opt,name=bind_info,json=bindInfo" json:"bind_info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *LoginData) Reset()                    { *m = LoginData{} }
func (m *LoginData) String() string            { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()               {}
func (*LoginData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginData) GetType() LoginType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return LoginType_PHONE_LOGIN
}

func (m *LoginData) GetChannel() ChannelType {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ChannelType_PHONE
}

func (m *LoginData) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *LoginData) GetDymcCode() string {
	if m != nil && m.DymcCode != nil {
		return *m.DymcCode
	}
	return ""
}

func (m *LoginData) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LoginData) GetProId() uint64 {
	if m != nil && m.ProId != nil {
		return *m.ProId
	}
	return 0
}

func (m *LoginData) GetCityId() uint64 {
	if m != nil && m.CityId != nil {
		return *m.CityId
	}
	return 0
}

func (m *LoginData) GetBindInfo() *BindInfo {
	if m != nil {
		return m.BindInfo
	}
	return nil
}

// 发送验证码
type AuthCodeReq struct {
	CellphoneNum     *uint64            `protobuf:"varint,1,opt,name=cellphone_num,json=cellphoneNum" json:"cellphone_num,omitempty"`
	SendCase         *AuthCodeSendScene `protobuf:"varint,2,opt,name=send_case,json=sendCase,enum=login.AuthCodeSendScene" json:"send_case,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *AuthCodeReq) Reset()                    { *m = AuthCodeReq{} }
func (m *AuthCodeReq) String() string            { return proto.CompactTextString(m) }
func (*AuthCodeReq) ProtoMessage()               {}
func (*AuthCodeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthCodeReq) GetCellphoneNum() uint64 {
	if m != nil && m.CellphoneNum != nil {
		return *m.CellphoneNum
	}
	return 0
}

func (m *AuthCodeReq) GetSendCase() AuthCodeSendScene {
	if m != nil && m.SendCase != nil {
		return *m.SendCase
	}
	return AuthCodeSendScene_REGISTER
}

// 验证码接收
type AuthCodeRsp struct {
	ErrorCode        *uint64 `protobuf:"varint,1,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
	ErrorMsg         *string `protobuf:"bytes,2,opt,name=ErrorMsg" json:"ErrorMsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthCodeRsp) Reset()                    { *m = AuthCodeRsp{} }
func (m *AuthCodeRsp) String() string            { return proto.CompactTextString(m) }
func (*AuthCodeRsp) ProtoMessage()               {}
func (*AuthCodeRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthCodeRsp) GetErrorCode() uint64 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *AuthCodeRsp) GetErrorMsg() string {
	if m != nil && m.ErrorMsg != nil {
		return *m.ErrorMsg
	}
	return ""
}

// LoginAuthReq 认证请求
type LoginAuthReq struct {
	AccountId   *uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	RequestData []byte  `protobuf:"bytes,2,opt,name=request_data,json=requestData" json:"request_data,omitempty"`
	// ...
	PlayerId         *uint64 `protobuf:"varint,14,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Token            *string `protobuf:"bytes,15,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginAuthReq) Reset()                    { *m = LoginAuthReq{} }
func (m *LoginAuthReq) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthReq) ProtoMessage()               {}
func (*LoginAuthReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginAuthReq) GetAccountId() uint64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *LoginAuthReq) GetRequestData() []byte {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (m *LoginAuthReq) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *LoginAuthReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// LoginAuthRsp 认证应答
type LoginAuthRsp struct {
	ErrCode          *ErrorCode `protobuf:"varint,1,opt,name=err_code,json=errCode,enum=login.ErrorCode" json:"err_code,omitempty"`
	PlayerId         *uint64    `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Token            *string    `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *LoginAuthRsp) Reset()                    { *m = LoginAuthRsp{} }
func (m *LoginAuthRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthRsp) ProtoMessage()               {}
func (*LoginAuthRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LoginAuthRsp) GetErrCode() ErrorCode {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return ErrorCode_SUCCESS
}

func (m *LoginAuthRsp) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *LoginAuthRsp) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// AccountSysLoginRequestData 账号系统登录消息
type AccountSysLoginRequestData struct {
	ProductId        *uint64 `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	Data             []byte  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountSysLoginRequestData) Reset()                    { *m = AccountSysLoginRequestData{} }
func (m *AccountSysLoginRequestData) String() string            { return proto.CompactTextString(m) }
func (*AccountSysLoginRequestData) ProtoMessage()               {}
func (*AccountSysLoginRequestData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AccountSysLoginRequestData) GetProductId() uint64 {
	if m != nil && m.ProductId != nil {
		return *m.ProductId
	}
	return 0
}

func (m *AccountSysLoginRequestData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*BindInfo)(nil), "login.BindInfo")
	proto.RegisterType((*LoginData)(nil), "login.LoginData")
	proto.RegisterType((*AuthCodeReq)(nil), "login.AuthCodeReq")
	proto.RegisterType((*AuthCodeRsp)(nil), "login.AuthCodeRsp")
	proto.RegisterType((*LoginAuthReq)(nil), "login.LoginAuthReq")
	proto.RegisterType((*LoginAuthRsp)(nil), "login.LoginAuthRsp")
	proto.RegisterType((*AccountSysLoginRequestData)(nil), "login.AccountSysLoginRequestData")
	proto.RegisterEnum("login.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("login.LoginType", LoginType_name, LoginType_value)
	proto.RegisterEnum("login.ChannelType", ChannelType_name, ChannelType_value)
	proto.RegisterEnum("login.AuthCodeSendScene", AuthCodeSendScene_name, AuthCodeSendScene_value)
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 726 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x5d, 0x6f, 0xdb, 0x36,
	0x14, 0x8d, 0x1c, 0x7f, 0x48, 0xd7, 0xae, 0xad, 0x70, 0x0d, 0xaa, 0xb5, 0x0b, 0x90, 0x79, 0x7b,
	0x08, 0xbc, 0xa2, 0xc5, 0x02, 0xec, 0x07, 0xc8, 0xb6, 0x90, 0x08, 0x53, 0xa5, 0x80, 0x72, 0x9b,
	0x61, 0x2f, 0x84, 0x42, 0x32, 0x8d, 0x30, 0x9b, 0x54, 0xf5, 0x31, 0xc3, 0xcf, 0xfb, 0x07, 0xfb,
	0xc5, 0x03, 0x29, 0x3a, 0x53, 0x31, 0xec, 0x8d, 0xe7, 0xdc, 0xcb, 0x7b, 0xce, 0xbd, 0x97, 0x84,
	0xf1, 0x56, 0x7e, 0xce, 0xc5, 0xbb, 0xa2, 0x94, 0xb5, 0x44, 0x03, 0x0d, 0xe6, 0x19, 0xd8, 0xcb,
	0x5c, 0xb0, 0x50, 0x3c, 0x4a, 0xf4, 0x2d, 0xd8, 0x7b, 0x4a, 0xb2, 0xa2, 0xc8, 0x99, 0x67, 0x5d,
	0x5a, 0x57, 0x0e, 0x1e, 0xed, 0xa9, 0xaf, 0x20, 0x7a, 0x03, 0xce, 0x9e, 0x12, 0x59, 0x70, 0x91,
	0x33, 0xaf, 0xa7, 0x63, 0xf6, 0x9e, 0x26, 0x1a, 0xa3, 0x0b, 0x80, 0x3d, 0x25, 0x8d, 0xc8, 0xa5,
	0x8a, 0x9e, 0xea, 0xa8, 0xb3, 0xa7, 0x1f, 0x5b, 0x62, 0xfe, 0x77, 0x0f, 0x9c, 0x48, 0x89, 0xad,
	0xb3, 0x3a, 0x43, 0x3f, 0x42, 0xbf, 0x3e, 0x14, 0x5c, 0x0b, 0x4c, 0xaf, 0xdd, 0x77, 0xad, 0x27,
	0x1d, 0xdf, 0x1c, 0x0a, 0x8e, 0x75, 0x14, 0xbd, 0x85, 0x11, 0x7d, 0xca, 0x84, 0xe0, 0x5b, 0xad,
	0x36, 0xbd, 0x46, 0x26, 0x71, 0xd5, 0xb2, 0x3a, 0xf5, 0x98, 0x82, 0x5e, 0x83, 0xdd, 0x54, 0xbc,
	0x14, 0xd9, 0x8e, 0x1b, 0xf9, 0x67, 0xac, 0x9c, 0xb3, 0xc3, 0x8e, 0x12, 0x2a, 0x19, 0xf7, 0xfa,
	0x6d, 0x50, 0x11, 0x2b, 0xc9, 0xb8, 0xba, 0x58, 0x64, 0x55, 0xb5, 0x97, 0x25, 0xf3, 0x06, 0x6d,
	0xec, 0x88, 0xd1, 0x39, 0x0c, 0x8b, 0x52, 0x92, 0x9c, 0x79, 0xc3, 0x4b, 0xeb, 0xaa, 0x8f, 0x07,
	0x45, 0x29, 0x43, 0x86, 0x5e, 0xc1, 0x88, 0xe6, 0xf5, 0x41, 0xf1, 0x23, 0xcd, 0x0f, 0x15, 0x0c,
	0x19, 0x7a, 0x0b, 0xce, 0x43, 0x2e, 0x18, 0xc9, 0xc5, 0xa3, 0xf4, 0xec, 0x4b, 0xeb, 0x6a, 0x7c,
	0x3d, 0x33, 0xa6, 0x8f, 0x13, 0xc6, 0xf6, 0x83, 0x39, 0xcd, 0x73, 0x18, 0xfb, 0x4d, 0xfd, 0xa4,
	0x5c, 0x60, 0xfe, 0x05, 0xfd, 0x00, 0x2f, 0x28, 0xdf, 0x6e, 0x8b, 0x27, 0x29, 0x38, 0x11, 0xcd,
	0x4e, 0x8f, 0xa7, 0x8f, 0x27, 0xcf, 0x64, 0xdc, 0xec, 0xd0, 0x2f, 0xe0, 0x54, 0x5c, 0x30, 0x42,
	0xb3, 0x8a, 0x9b, 0xb1, 0x78, 0x46, 0xe1, 0x58, 0x2b, 0xe5, 0x82, 0xa5, 0x94, 0x0b, 0x8e, 0x6d,
	0x95, 0xba, 0xca, 0x2a, 0x3e, 0xbf, 0xe9, 0x48, 0x55, 0x05, 0xfa, 0x0e, 0x9c, 0xa0, 0x2c, 0x65,
	0xa9, 0xb0, 0x91, 0xf9, 0x97, 0x50, 0x13, 0xd1, 0xe0, 0x43, 0xf5, 0xf9, 0xb8, 0xe7, 0x23, 0x9e,
	0xff, 0x65, 0xc1, 0x44, 0x2f, 0x4a, 0x95, 0x53, 0xae, 0x2f, 0x00, 0x32, 0x4a, 0x65, 0x23, 0x6a,
	0x62, 0x9e, 0x4c, 0x1f, 0x3b, 0x86, 0x09, 0x19, 0xfa, 0x1e, 0x26, 0x25, 0xff, 0xd2, 0xf0, 0xaa,
	0x26, 0x2c, 0xab, 0x33, 0x5d, 0x6f, 0x82, 0xc7, 0x86, 0xd3, 0xaf, 0xe1, 0x0d, 0x38, 0xc5, 0x36,
	0x3b, 0xf0, 0x52, 0x15, 0x98, 0xea, 0x02, 0x76, 0x4b, 0x84, 0x0c, 0xbd, 0x84, 0x41, 0x2d, 0xff,
	0xe0, 0xc2, 0x9b, 0x69, 0x23, 0x2d, 0x98, 0x8b, 0xae, 0x89, 0xaa, 0x40, 0x3f, 0x81, 0xcd, 0xcb,
	0xb2, 0xdd, 0xef, 0xd7, 0x8f, 0xea, 0xb9, 0x2b, 0x3c, 0xe2, 0x65, 0xdb, 0xde, 0x57, 0x7a, 0xbd,
	0xff, 0xd3, 0x3b, 0xed, 0xea, 0x25, 0xf0, 0xda, 0x6f, 0x5b, 0x4a, 0x0f, 0x95, 0x56, 0xc6, 0x9d,
	0x06, 0x2e, 0x00, 0x8a, 0x52, 0xb2, 0x86, 0x76, 0x47, 0x60, 0x98, 0x90, 0x21, 0x04, 0xfd, 0x4e,
	0xeb, 0xfa, 0xbc, 0x48, 0x3b, 0x0b, 0x40, 0x63, 0x18, 0xa5, 0x1f, 0x57, 0xab, 0x20, 0x4d, 0xdd,
	0x13, 0x34, 0x01, 0xdb, 0x5f, 0xc6, 0x09, 0xfe, 0xe0, 0x47, 0xae, 0x85, 0x5e, 0x82, 0x1b, 0x60,
	0x4c, 0x82, 0xdf, 0xee, 0x42, 0x1c, 0x90, 0x4d, 0xf2, 0x6b, 0x10, 0xbb, 0x1c, 0x9d, 0xc3, 0x99,
	0x62, 0xc3, 0xf8, 0x93, 0x1f, 0x85, 0x6b, 0x43, 0x3f, 0x2e, 0x7c, 0xf3, 0xc7, 0xd4, 0xc7, 0x40,
	0x33, 0x18, 0xdf, 0xdd, 0x26, 0x71, 0x40, 0xa2, 0xe4, 0x26, 0x8c, 0xdd, 0x13, 0xe4, 0xc2, 0xe4,
	0x3e, 0x58, 0xdd, 0xfa, 0x1b, 0xc3, 0x58, 0xe8, 0x0c, 0x5e, 0x7c, 0x0a, 0xd3, 0x70, 0x93, 0x60,
	0x43, 0xf5, 0x16, 0x3f, 0xc3, 0xb8, 0xf3, 0xbb, 0x90, 0x03, 0x03, 0x5d, 0xc4, 0x3d, 0x41, 0x00,
	0xc3, 0xf6, 0xba, 0x6b, 0x29, 0xc3, 0xe6, 0xa2, 0xdb, 0x5b, 0x48, 0x38, 0xfb, 0xcf, 0xcb, 0x53,
	0x5d, 0xe0, 0xe0, 0x26, 0x4c, 0x37, 0x01, 0x76, 0x2d, 0x84, 0x60, 0x8a, 0x83, 0x34, 0xd8, 0x90,
	0x3b, 0x3f, 0x4d, 0xef, 0x13, 0xbc, 0x76, 0x7b, 0xe8, 0x1b, 0x98, 0xb5, 0xdc, 0x2a, 0x88, 0xa2,
	0x56, 0xe4, 0x54, 0x25, 0xc6, 0xc1, 0x3d, 0xb9, 0xf5, 0xa3, 0xc8, 0x58, 0xea, 0xab, 0x46, 0x96,
	0x61, 0xbc, 0x26, 0x46, 0x1d, 0x96, 0xaf, 0x7e, 0x3f, 0xaf, 0x6a, 0xfe, 0x27, 0x7f, 0x4f, 0xb7,
	0x39, 0x17, 0x35, 0x29, 0x1e, 0xde, 0xeb, 0x5d, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x91, 0xdf,
	0x41, 0x10, 0xdc, 0x04, 0x00, 0x00,
}
