// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package login is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	LoginAuthReq
	LoginAuthRsp
*/
package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_SUCCESS           ErrorCode = 0
	ErrorCode_ABNORMAL          ErrorCode = 1
	ErrorCode_ERR_EXPIRE_TOKEN  ErrorCode = 101
	ErrorCode_ERR_INVALID_TOKEN ErrorCode = 102
)

var ErrorCode_name = map[int32]string{
	0:   "SUCCESS",
	1:   "ABNORMAL",
	101: "ERR_EXPIRE_TOKEN",
	102: "ERR_INVALID_TOKEN",
}
var ErrorCode_value = map[string]int32{
	"SUCCESS":           0,
	"ABNORMAL":          1,
	"ERR_EXPIRE_TOKEN":  101,
	"ERR_INVALID_TOKEN": 102,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// LoginAuthReq 认证请求
type LoginAuthReq struct {
	AccountId   *uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	RequestData []byte  `protobuf:"bytes,2,opt,name=request_data,json=requestData" json:"request_data,omitempty"`
	// ...
	PlayerId         *uint64 `protobuf:"varint,14,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Token            *string `protobuf:"bytes,15,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginAuthReq) Reset()                    { *m = LoginAuthReq{} }
func (m *LoginAuthReq) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthReq) ProtoMessage()               {}
func (*LoginAuthReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginAuthReq) GetAccountId() uint64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *LoginAuthReq) GetRequestData() []byte {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (m *LoginAuthReq) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *LoginAuthReq) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

// LoginAuthRsp 认证应答
type LoginAuthRsp struct {
	ErrCode          *ErrorCode `protobuf:"varint,1,opt,name=err_code,json=errCode,enum=login.ErrorCode" json:"err_code,omitempty"`
	PlayerId         *uint64    `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Token            *string    `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *LoginAuthRsp) Reset()                    { *m = LoginAuthRsp{} }
func (m *LoginAuthRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthRsp) ProtoMessage()               {}
func (*LoginAuthRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginAuthRsp) GetErrCode() ErrorCode {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return ErrorCode_SUCCESS
}

func (m *LoginAuthRsp) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *LoginAuthRsp) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginAuthReq)(nil), "login.LoginAuthReq")
	proto.RegisterType((*LoginAuthRsp)(nil), "login.LoginAuthRsp")
	proto.RegisterEnum("login.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8e, 0x4d, 0x4b, 0xc3, 0x40,
	0x18, 0x84, 0xdd, 0x6a, 0x69, 0xf3, 0x36, 0xd4, 0xb8, 0xb4, 0x58, 0x10, 0xa1, 0xf6, 0x54, 0x14,
	0x5a, 0xf0, 0x1f, 0xa4, 0xed, 0x1e, 0x82, 0xb5, 0x95, 0x8d, 0x8a, 0x78, 0x59, 0xd6, 0xec, 0xab,
	0x06, 0x43, 0x36, 0xdd, 0x6c, 0x04, 0xcf, 0xfe, 0x71, 0xc9, 0x07, 0x52, 0x0f, 0xde, 0x66, 0x9e,
	0xc3, 0xcc, 0x03, 0xbd, 0x44, 0xbf, 0xc5, 0xe9, 0x2c, 0x33, 0xda, 0x6a, 0xda, 0xae, 0xca, 0xe4,
	0x9b, 0x80, 0xbb, 0x2e, 0x93, 0x5f, 0xd8, 0x77, 0x8e, 0x3b, 0x7a, 0x0e, 0x20, 0xa3, 0x48, 0x17,
	0xa9, 0x15, 0xb1, 0x1a, 0x91, 0x31, 0x99, 0x1e, 0x71, 0xa7, 0x21, 0x81, 0xa2, 0x17, 0xe0, 0x1a,
	0xdc, 0x15, 0x98, 0x5b, 0xa1, 0xa4, 0x95, 0xa3, 0xd6, 0x98, 0x4c, 0x5d, 0xde, 0x6b, 0xd8, 0x4a,
	0x5a, 0x49, 0xcf, 0xc0, 0xc9, 0x12, 0xf9, 0x85, 0xa6, 0x1c, 0xe8, 0x57, 0x03, 0xdd, 0x1a, 0x04,
	0x8a, 0x0e, 0xa0, 0x6d, 0xf5, 0x07, 0xa6, 0xa3, 0xe3, 0x31, 0x99, 0x3a, 0xbc, 0x2e, 0x93, 0x74,
	0x5f, 0x22, 0xcf, 0xe8, 0x15, 0x74, 0xd1, 0x18, 0x11, 0x69, 0x85, 0x95, 0x42, 0xff, 0xda, 0x9b,
	0xd5, 0xf2, 0xcc, 0x18, 0x6d, 0x96, 0x5a, 0x21, 0xef, 0xa0, 0xa9, 0xc2, 0xdf, 0xbf, 0xd6, 0x7f,
	0x7f, 0x87, 0x7b, 0x7f, 0x97, 0x21, 0x38, 0xbf, 0x43, 0xb4, 0x07, 0x9d, 0xf0, 0x61, 0xb9, 0x64,
	0x61, 0xe8, 0x1d, 0x50, 0x17, 0xba, 0xfe, 0x62, 0xb3, 0xe5, 0xb7, 0xfe, 0xda, 0x23, 0x74, 0x00,
	0x1e, 0xe3, 0x5c, 0xb0, 0xa7, 0xbb, 0x80, 0x33, 0x71, 0xbf, 0xbd, 0x61, 0x1b, 0x0f, 0xe9, 0x10,
	0x4e, 0x4a, 0x1a, 0x6c, 0x1e, 0xfd, 0x75, 0xb0, 0x6a, 0xf0, 0xeb, 0xe2, 0xf4, 0x79, 0x98, 0x5b,
	0xfc, 0xc4, 0x79, 0x94, 0xc4, 0x98, 0x5a, 0x91, 0xbd, 0xcc, 0x2b, 0xe7, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x59, 0x8a, 0x0b, 0x3c, 0x78, 0x01, 0x00, 0x00,
}
