
#### service loader configs
# log 
log_level: debug 
log_dir: ./log
log_prefix: login 
log_stderr: true 

# redis 
redis_addr: 127.0.0.1:6379
redis_passwd: 

# nsq 
nsqd_addr: 127.0.0.1:4150
nsqlookupd_addrs: 
  - 127.0.0.1:4161

# consul 
consul_addr: 127.0.0.1:8500

rpc_addr: 127.0.0.1
rpc_port: 36201
health_port: 36202
rpc_server_name: login


redis_list:
  player: 
    addr: 127.0.0.1:6379
    passwd: 

node: 1

# 内部认证，不通过账号系统
inner_auth: true  

# 账号系统登录 url 
login_url: http://192.168.7.26:8086/mock/24/account/loginv2

# 产品 ID 
product_id: 9999



