log_level: debug 
log_dir: ./log
log_prefix: gateway
log_stderr: true 

# rpc_addr: 127.0.0.1
# rpc_port: 36002
# rpc_server_name: gate

lis_client_addr: 192.168.8.148
lis_client_port: 36001

peipai_addr: 192.168.8.148:36002

