log_level: debug 
log_dir: ./log
log_prefix: match
log_stderr: true 

rpc_addr: 192.168.8.17
rpc_port: 37001
rpc_server_name: match
health_port: 17001


redis_addr: 192.168.7.108:6379
redis_passwd: 

consul_addr: 192.168.7.108:8500

nsqd_addr: 192.168.7.108:4150
nsqlookupd_addrs: 
  - 192.168.7.108:4161


