log_level: debug 
log_dir: ./log
log_prefix: room
log_stderr: true 

rpc_addr: 127.0.0.1
rpc_port: 36100
rpc_server_name: room

peipai_addr: 0.0.0.0:36102

# redis 
redis_addr: 127.0.0.1:6379
redis_passwd: 

redis_list:
  player: 
    addr: 127.0.0.1:6379
    passwd:   

consul_addr: 127.0.0.1:8500

nsqd_addr: 127.0.0.1:4150
nsqlookupd_addrs: 
  - 127.0.0.1:4161


# mysql 数据库列表
mysql_list:
  log:
    user: root
    passwd: 123456
    addr: 127.0.0.1:3306
    db: log 
    params:
      charset: utf8
  player:
    user: backuser
    passwd: Sdf123esdf
    addr: 192.168.7.108:3306 
    db: player 
    params:
      charset: utf8
  config:
    user: backuser
    passwd: Sdf123esdf 
    addr: 192.168.7.108:3306
    db: config   
    params:
      charset: utf8 

node: 1

ai:
  visible: false