#日志配置
log_level: debug
log_dir: ./log
log_prefix: gold
log_stderr: true 

#RPC服务地址
rpc_addr: 192.168.8.17
#RPC服务监听Port
rpc_port: 36301
#RPC服务名
rpc_server_name: gold
#RPC服务组名
#group_name: 1000,1001
#RPC服务健康监控Port
health_port: 16301

#redis 配置
redis_addr: 192.168.7.108:6379
redis_passwd:

#consul 服务中心配置
consul_addr: 192.168.7.108:8500

#nsq 消息队列配置
nsqd_addr: 192.168.7.108:4150
nsqlookupd_addrs:
  - 192.168.7.108:4161