// Code generated by protoc-gen-go. DO NOT EDIT.
// source: props.proto

package props

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 返回结果
type ResultStat int32

const (
	ResultStat_SUCCEED       ResultStat = 0
	ResultStat_FAILED        ResultStat = 1
	ResultStat_ERR_SEQ_NO    ResultStat = 2
	ResultStat_ERR_NO_USER   ResultStat = 3
	ResultStat_ERR_NO_PROPS  ResultStat = 4
	ResultStat_ERR_UID_ERROR ResultStat = 5
	ResultStat_ERR_ARG       ResultStat = 6
)

var ResultStat_name = map[int32]string{
	0: "SUCCEED",
	1: "FAILED",
	2: "ERR_SEQ_NO",
	3: "ERR_NO_USER",
	4: "ERR_NO_PROPS",
	5: "ERR_UID_ERROR",
	6: "ERR_ARG",
}
var ResultStat_value = map[string]int32{
	"SUCCEED":       0,
	"FAILED":        1,
	"ERR_SEQ_NO":    2,
	"ERR_NO_USER":   3,
	"ERR_NO_PROPS":  4,
	"ERR_UID_ERROR": 5,
	"ERR_ARG":       6,
}

func (x ResultStat) String() string {
	return proto.EnumName(ResultStat_name, int32(x))
}
func (ResultStat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_props_ea133dff7f9ffaae, []int{0}
}

// 道具
type PropsInfo struct {
	PropsId              uint64   `protobuf:"varint,1,opt,name=props_id,json=propsId,proto3" json:"props_id,omitempty"`
	AddNum               int64    `protobuf:"varint,2,opt,name=add_num,json=addNum,proto3" json:"add_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropsInfo) Reset()         { *m = PropsInfo{} }
func (m *PropsInfo) String() string { return proto.CompactTextString(m) }
func (*PropsInfo) ProtoMessage()    {}
func (*PropsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_props_ea133dff7f9ffaae, []int{0}
}
func (m *PropsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropsInfo.Unmarshal(m, b)
}
func (m *PropsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropsInfo.Marshal(b, m, deterministic)
}
func (dst *PropsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropsInfo.Merge(dst, src)
}
func (m *PropsInfo) XXX_Size() int {
	return xxx_messageInfo_PropsInfo.Size(m)
}
func (m *PropsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PropsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PropsInfo proto.InternalMessageInfo

func (m *PropsInfo) GetPropsId() uint64 {
	if m != nil {
		return m.PropsId
	}
	return 0
}

func (m *PropsInfo) GetAddNum() int64 {
	if m != nil {
		return m.AddNum
	}
	return 0
}

// 添加道具请求
type AddPropsReq struct {
	Uid                  uint64       `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PropsList            []*PropsInfo `protobuf:"bytes,2,rep,name=props_list,json=propsList,proto3" json:"props_list,omitempty"`
	FuncId               int32        `protobuf:"varint,3,opt,name=func_id,json=funcId,proto3" json:"func_id,omitempty"`
	Seq                  string       `protobuf:"bytes,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Channel              int64        `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Time                 int64        `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	GameId               int32        `protobuf:"varint,7,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Level                int32        `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddPropsReq) Reset()         { *m = AddPropsReq{} }
func (m *AddPropsReq) String() string { return proto.CompactTextString(m) }
func (*AddPropsReq) ProtoMessage()    {}
func (*AddPropsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_props_ea133dff7f9ffaae, []int{1}
}
func (m *AddPropsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPropsReq.Unmarshal(m, b)
}
func (m *AddPropsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPropsReq.Marshal(b, m, deterministic)
}
func (dst *AddPropsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPropsReq.Merge(dst, src)
}
func (m *AddPropsReq) XXX_Size() int {
	return xxx_messageInfo_AddPropsReq.Size(m)
}
func (m *AddPropsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPropsReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddPropsReq proto.InternalMessageInfo

func (m *AddPropsReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AddPropsReq) GetPropsList() []*PropsInfo {
	if m != nil {
		return m.PropsList
	}
	return nil
}

func (m *AddPropsReq) GetFuncId() int32 {
	if m != nil {
		return m.FuncId
	}
	return 0
}

func (m *AddPropsReq) GetSeq() string {
	if m != nil {
		return m.Seq
	}
	return ""
}

func (m *AddPropsReq) GetChannel() int64 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *AddPropsReq) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *AddPropsReq) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *AddPropsReq) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

// 添加道具回复
type AddPropsRsp struct {
	ErrCode              ResultStat `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=props.ResultStat" json:"err_code,omitempty"`
	ErrDesc              string     `protobuf:"bytes,2,opt,name=err_desc,json=errDesc,proto3" json:"err_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddPropsRsp) Reset()         { *m = AddPropsRsp{} }
func (m *AddPropsRsp) String() string { return proto.CompactTextString(m) }
func (*AddPropsRsp) ProtoMessage()    {}
func (*AddPropsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_props_ea133dff7f9ffaae, []int{2}
}
func (m *AddPropsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPropsRsp.Unmarshal(m, b)
}
func (m *AddPropsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPropsRsp.Marshal(b, m, deterministic)
}
func (dst *AddPropsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPropsRsp.Merge(dst, src)
}
func (m *AddPropsRsp) XXX_Size() int {
	return xxx_messageInfo_AddPropsRsp.Size(m)
}
func (m *AddPropsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPropsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddPropsRsp proto.InternalMessageInfo

func (m *AddPropsRsp) GetErrCode() ResultStat {
	if m != nil {
		return m.ErrCode
	}
	return ResultStat_SUCCEED
}

func (m *AddPropsRsp) GetErrDesc() string {
	if m != nil {
		return m.ErrDesc
	}
	return ""
}

// 获取项
type GetItem struct {
	PropsId              uint64   `protobuf:"varint,1,opt,name=props_id,json=propsId,proto3" json:"props_id,omitempty"`
	PropsNum             int64    `protobuf:"varint,2,opt,name=props_num,json=propsNum,proto3" json:"props_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItem) Reset()         { *m = GetItem{} }
func (m *GetItem) String() string { return proto.CompactTextString(m) }
func (*GetItem) ProtoMessage()    {}
func (*GetItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_props_ea133dff7f9ffaae, []int{3}
}
func (m *GetItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItem.Unmarshal(m, b)
}
func (m *GetItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItem.Marshal(b, m, deterministic)
}
func (dst *GetItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItem.Merge(dst, src)
}
func (m *GetItem) XXX_Size() int {
	return xxx_messageInfo_GetItem.Size(m)
}
func (m *GetItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetItem proto.InternalMessageInfo

func (m *GetItem) GetPropsId() uint64 {
	if m != nil {
		return m.PropsId
	}
	return 0
}

func (m *GetItem) GetPropsNum() int64 {
	if m != nil {
		return m.PropsNum
	}
	return 0
}

// 获取玩家道具列表请求
type GetPropsReq struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PropsId              uint64   `protobuf:"varint,2,opt,name=props_id,json=propsId,proto3" json:"props_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPropsReq) Reset()         { *m = GetPropsReq{} }
func (m *GetPropsReq) String() string { return proto.CompactTextString(m) }
func (*GetPropsReq) ProtoMessage()    {}
func (*GetPropsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_props_ea133dff7f9ffaae, []int{4}
}
func (m *GetPropsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPropsReq.Unmarshal(m, b)
}
func (m *GetPropsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPropsReq.Marshal(b, m, deterministic)
}
func (dst *GetPropsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPropsReq.Merge(dst, src)
}
func (m *GetPropsReq) XXX_Size() int {
	return xxx_messageInfo_GetPropsReq.Size(m)
}
func (m *GetPropsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPropsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPropsReq proto.InternalMessageInfo

func (m *GetPropsReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetPropsReq) GetPropsId() uint64 {
	if m != nil {
		return m.PropsId
	}
	return 0
}

//  获取玩家道具列表回复
type GetPropsRsp struct {
	ErrCode              ResultStat `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=props.ResultStat" json:"err_code,omitempty"`
	ErrDesc              string     `protobuf:"bytes,2,opt,name=err_desc,json=errDesc,proto3" json:"err_desc,omitempty"`
	PropsList            []*GetItem `protobuf:"bytes,3,rep,name=props_list,json=propsList,proto3" json:"props_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetPropsRsp) Reset()         { *m = GetPropsRsp{} }
func (m *GetPropsRsp) String() string { return proto.CompactTextString(m) }
func (*GetPropsRsp) ProtoMessage()    {}
func (*GetPropsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_props_ea133dff7f9ffaae, []int{5}
}
func (m *GetPropsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPropsRsp.Unmarshal(m, b)
}
func (m *GetPropsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPropsRsp.Marshal(b, m, deterministic)
}
func (dst *GetPropsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPropsRsp.Merge(dst, src)
}
func (m *GetPropsRsp) XXX_Size() int {
	return xxx_messageInfo_GetPropsRsp.Size(m)
}
func (m *GetPropsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPropsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPropsRsp proto.InternalMessageInfo

func (m *GetPropsRsp) GetErrCode() ResultStat {
	if m != nil {
		return m.ErrCode
	}
	return ResultStat_SUCCEED
}

func (m *GetPropsRsp) GetErrDesc() string {
	if m != nil {
		return m.ErrDesc
	}
	return ""
}

func (m *GetPropsRsp) GetPropsList() []*GetItem {
	if m != nil {
		return m.PropsList
	}
	return nil
}

func init() {
	proto.RegisterType((*PropsInfo)(nil), "props.PropsInfo")
	proto.RegisterType((*AddPropsReq)(nil), "props.AddPropsReq")
	proto.RegisterType((*AddPropsRsp)(nil), "props.AddPropsRsp")
	proto.RegisterType((*GetItem)(nil), "props.GetItem")
	proto.RegisterType((*GetPropsReq)(nil), "props.GetPropsReq")
	proto.RegisterType((*GetPropsRsp)(nil), "props.GetPropsRsp")
	proto.RegisterEnum("props.ResultStat", ResultStat_name, ResultStat_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PropsClient is the client API for Props service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PropsClient interface {
	// 添加用户道具
	AddUserProps(ctx context.Context, in *AddPropsReq, opts ...grpc.CallOption) (*AddPropsRsp, error)
	// 获取玩家道具列表
	GetUserProps(ctx context.Context, in *GetPropsReq, opts ...grpc.CallOption) (*GetPropsRsp, error)
}

type propsClient struct {
	cc *grpc.ClientConn
}

func NewPropsClient(cc *grpc.ClientConn) PropsClient {
	return &propsClient{cc}
}

func (c *propsClient) AddUserProps(ctx context.Context, in *AddPropsReq, opts ...grpc.CallOption) (*AddPropsRsp, error) {
	out := new(AddPropsRsp)
	err := c.cc.Invoke(ctx, "/props.Props/AddUserProps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propsClient) GetUserProps(ctx context.Context, in *GetPropsReq, opts ...grpc.CallOption) (*GetPropsRsp, error) {
	out := new(GetPropsRsp)
	err := c.cc.Invoke(ctx, "/props.Props/GetUserProps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropsServer is the server API for Props service.
type PropsServer interface {
	// 添加用户道具
	AddUserProps(context.Context, *AddPropsReq) (*AddPropsRsp, error)
	// 获取玩家道具列表
	GetUserProps(context.Context, *GetPropsReq) (*GetPropsRsp, error)
}

func RegisterPropsServer(s *grpc.Server, srv PropsServer) {
	s.RegisterService(&_Props_serviceDesc, srv)
}

func _Props_AddUserProps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPropsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropsServer).AddUserProps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/props.Props/AddUserProps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropsServer).AddUserProps(ctx, req.(*AddPropsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Props_GetUserProps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPropsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropsServer).GetUserProps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/props.Props/GetUserProps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropsServer).GetUserProps(ctx, req.(*GetPropsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Props_serviceDesc = grpc.ServiceDesc{
	ServiceName: "props.Props",
	HandlerType: (*PropsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUserProps",
			Handler:    _Props_AddUserProps_Handler,
		},
		{
			MethodName: "GetUserProps",
			Handler:    _Props_GetUserProps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "props.proto",
}

func init() { proto.RegisterFile("props.proto", fileDescriptor_props_ea133dff7f9ffaae) }

var fileDescriptor_props_ea133dff7f9ffaae = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xe3, 0xd8, 0x4e, 0xc6, 0x25, 0x6c, 0x47, 0x08, 0x4c, 0xb9, 0x44, 0x3e, 0x45, 0x08,
	0x8a, 0x14, 0x2e, 0x88, 0x0b, 0xb2, 0x12, 0x13, 0x59, 0xaa, 0x92, 0xb0, 0x56, 0xb8, 0x5a, 0xc6,
	0xbb, 0x85, 0x48, 0xfe, 0xaa, 0x77, 0x8d, 0x90, 0x38, 0xf3, 0x1b, 0xf9, 0x3b, 0x68, 0xd7, 0xa6,
	0xb8, 0x8a, 0xd4, 0x13, 0xb7, 0x79, 0x2f, 0x3b, 0x6f, 0xe6, 0xbd, 0x89, 0xc1, 0xad, 0x9b, 0xaa,
	0x16, 0x57, 0x75, 0x53, 0xc9, 0x0a, 0x2d, 0x0d, 0xfc, 0x0f, 0x30, 0xdd, 0xab, 0x22, 0x2a, 0x6f,
	0x2a, 0x7c, 0x0e, 0x13, 0xcd, 0x26, 0x47, 0xe6, 0x19, 0x73, 0x63, 0x31, 0xa6, 0x8e, 0xc6, 0x11,
	0xc3, 0x67, 0xe0, 0xa4, 0x8c, 0x25, 0x65, 0x5b, 0x78, 0xa3, 0xb9, 0xb1, 0x30, 0xa9, 0x9d, 0x32,
	0xb6, 0x6d, 0x0b, 0xff, 0xb7, 0x01, 0x6e, 0xc0, 0x98, 0x16, 0xa1, 0xfc, 0x16, 0x09, 0x98, 0xed,
	0x5d, 0xbb, 0x2a, 0xf1, 0x0d, 0x40, 0xa7, 0x9a, 0x1f, 0x85, 0xf4, 0x46, 0x73, 0x73, 0xe1, 0x2e,
	0xc9, 0x55, 0xb7, 0xcb, 0xdd, 0x6c, 0x3a, 0xd5, 0xc4, 0xf5, 0x51, 0x48, 0x35, 0xeb, 0xa6, 0x2d,
	0x33, 0xb5, 0x85, 0x39, 0x37, 0x16, 0x16, 0xb5, 0x15, 0x8c, 0x98, 0xd2, 0x16, 0xfc, 0xd6, 0x1b,
	0xcf, 0x8d, 0xc5, 0x94, 0xaa, 0x12, 0x3d, 0x70, 0xb2, 0x6f, 0x69, 0x59, 0xf2, 0xdc, 0xb3, 0xf4,
	0x5a, 0x7f, 0x21, 0x22, 0x8c, 0xe5, 0xb1, 0xe0, 0x9e, 0xad, 0x69, 0x5d, 0xe3, 0x53, 0xb0, 0xbf,
	0xa6, 0x05, 0x8f, 0x98, 0xe7, 0x74, 0xba, 0x1d, 0xc2, 0x27, 0x60, 0xe5, 0xfc, 0x3b, 0xcf, 0xbd,
	0x89, 0xa6, 0x3b, 0xe0, 0x7f, 0x1e, 0x18, 0x13, 0x35, 0xbe, 0x82, 0x09, 0x6f, 0x9a, 0x24, 0xab,
	0x18, 0xd7, 0xee, 0x66, 0xcb, 0x8b, 0xde, 0x04, 0xe5, 0xa2, 0xcd, 0x65, 0x2c, 0x53, 0x49, 0x1d,
	0xde, 0x34, 0xab, 0x8a, 0x71, 0x15, 0xa5, 0x7a, 0xcd, 0xb8, 0xc8, 0x74, 0x60, 0x53, 0xfd, 0xd3,
	0x9a, 0x8b, 0xcc, 0x0f, 0xc0, 0xd9, 0x70, 0x19, 0x49, 0x5e, 0x3c, 0x14, 0xf8, 0x0b, 0xe8, 0x12,
	0x19, 0x44, 0xde, 0xbd, 0x55, 0xa1, 0xbf, 0x07, 0x77, 0xc3, 0xe5, 0x03, 0x99, 0x0f, 0x85, 0x47,
	0xf7, 0x84, 0xfd, 0x5f, 0xc6, 0xa0, 0xf9, 0x3f, 0xfa, 0xc2, 0xd7, 0xf7, 0xee, 0x6c, 0xea, 0x3b,
	0xcf, 0x7a, 0xa9, 0xde, 0xf0, 0xe0, 0xca, 0x2f, 0x7f, 0x00, 0xfc, 0x1b, 0x80, 0x2e, 0x38, 0xf1,
	0x61, 0xb5, 0x0a, 0xc3, 0x35, 0x39, 0x43, 0x00, 0xfb, 0x63, 0x10, 0x5d, 0x87, 0x6b, 0x62, 0xe0,
	0x0c, 0x20, 0xa4, 0x34, 0x89, 0xc3, 0x4f, 0xc9, 0x76, 0x47, 0x46, 0xf8, 0x18, 0x5c, 0x85, 0xb7,
	0xbb, 0xe4, 0x10, 0x87, 0x94, 0x98, 0x48, 0xe0, 0xbc, 0x27, 0xf6, 0x74, 0xb7, 0x8f, 0xc9, 0x18,
	0x2f, 0xe0, 0x91, 0x62, 0x0e, 0xd1, 0x3a, 0x09, 0x29, 0xdd, 0x51, 0x62, 0x29, 0x79, 0x45, 0x05,
	0x74, 0x43, 0xec, 0xe5, 0x4f, 0xb0, 0xb4, 0x7b, 0x7c, 0x07, 0xe7, 0x01, 0x63, 0x07, 0xc1, 0x9b,
	0x0e, 0x63, 0xbf, 0xed, 0xe0, 0xff, 0x7c, 0x79, 0xc2, 0x89, 0xda, 0x3f, 0x53, 0x9d, 0x1b, 0x2e,
	0x4f, 0x3b, 0x07, 0x57, 0xb9, 0x3c, 0xe1, 0x54, 0xe7, 0x17, 0x5b, 0x7f, 0x7e, 0x6f, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xc4, 0x82, 0xfc, 0x22, 0x8d, 0x03, 0x00, 0x00,
}
