package configutil

func main() {
	/* 	json := `[{
	"gameID":1,
	"levelID":1,
	"name":"新手场",
	"fee":1,
	"baseScores":1,
	"lowScores":100,
	"highScores":1000000,
	"realOnlinePeople":1,
	"showOnlinePeople":1,
	"status":1,
	"tag":null,
	"isAlms":1,
	"remark":null
	},
	{
	"gameID":2,
	"levelID":1,
	"name":"新手场",
	"fee":1,
	"baseScores":1,
	"lowScores":0,
	"highScores":1000000,
	"realOnlinePeople":1,
	"showOnlinePeople":1,
	"status":1,
	"tag":null,
	"isAlms":1,
	"remark":null
	},
	{
	"gameID":3,
	"levelID":1,
	"name":"新手场",
	"fee":1,
	"baseScores":1,
	"lowScores":0,
	"highScores":1000000,
	"realOnlinePeople":1,
	"showOnlinePeople":1,
	"status":1,
	"tag":null,
	"isAlms":1,
	"remark":null
	},
	{
	"gameID":4,
	"levelID":1,
	"name":"新手场",
	"fee":1,
	"baseScores":2,
	"lowScores":0,
	"highScores":1000000,
	"realOnlinePeople":1,
	"showOnlinePeople":1,
	"status":1,
	"tag":null,
	"isAlms":1,
	"remark":null
	}]`
	ParseToGameLevelConfigMap(json) */
}
